---
version: "2"
services: 
 ruuvitags2mqtt:
    container_name: ruuvitags2mqtt
    privileged: true
    restart: unless-stopped
    build: .
    volumes:
      - ./tag_names.yml.example:/tag_names.yml
    environment:
      MQTT_HOST: mqtt
