---
# Example docker-compose.yml that sets up mqtt and home assistant
version: "2"
services: 
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: unless-stopped
    volumes:
    - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
    - 1883:1883
  hass:
    depends_on:
    - mqtt
    container_name: hass
    restart: unless-stopped
    image: "ghcr.io/home-assistant/home-assistant:stable"
    ports:
    - 8123:8123
  ruuvitags2mqtt:
    depends_on:
    - mqtt
    container_name: ruuvitags2mqtt
    privileged: true
    network_mode: host
    restart: unless-stopped
    build: .
    volumes:
    - ./tag_names.yml:/tag_names.yml
    environment:
      MQTT_HOST: 127.0.0.1
      HCI_DEVICE: hci1
      HASS_AUTODISCOVERY: True
